version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "127.0.0.1:8050:8050"
    extra_hosts:
      - "host.docker.internal:host-gateway"